const ExamsData = [
  {
    "id": 1,
    "name": "Chest 2 View",
    "region": "Chest",
    "common": true,
    "shortcut": true,
    "cptCode": { "id": 1, "cptCode": "71046" },
    "anatomy": { "id": 1, "name": "Chest" },
    "views": { "id": 1, "name": "PA + Lateral" },
    "description": { "id": 1, "text": "PA and lateral; include apices to costophrenic angles." },
    "alias": { "id": 1, "name": "CXR" }
  },
  {
    "id": 2,
    "name": "Chest 1 View",
    "region": "Chest",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 2, "cptCode": "71045" },
    "anatomy": { "id": 1, "name": "Chest" },
    "views": { "id": 2, "name": "AP Portable" },
    "description": { "id": 2, "text": "AP supine/upright; include apices to costophrenic angles." },
    "alias": { "id": 2, "name": "Portable Chest" }
  },
  {
    "id": 3,
    "name": "C-Spine 2-3 View",
    "region": "Cervical Spine",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 3, "cptCode": "72040" },
    "anatomy": { "id": 2, "name": "Cervical Spine" },
    "views": { "id": 3, "name": "AP + Lat + Odontoid" },
    "description": { "id": 3, "text": "AP, lateral, and odontoid; include C1–C7." },
    "alias": { "id": 3, "name": "C-Spine Basic" }
  },
  {
    "id": 4,
    "name": "Abdomen KUB",
    "region": "Abdomen",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 4, "cptCode": "74018" },
    "anatomy": { "id": 3, "name": "Abdomen" },
    "views": { "id": 4, "name": "AP Supine" },
    "description": { "id": 4, "text": "Center at iliac crest; include diaphragm + symphysis." },
    "alias": { "id": 4, "name": "KUB" }
  },
  {
    "id": 5,
    "name": "Foot 3 View",
    "region": "Lower Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 5, "cptCode": "73630" },
    "anatomy": { "id": 4, "name": "Foot" },
    "views": { "id": 5, "name": "AP + Lat + Oblique" },
    "description": { "id": 5, "text": "Include toes to calcaneus." },
    "alias": { "id": 5, "name": "Foot Complete" }
  },
  {
    "id": 6,
    "name": "Hand 3 View",
    "region": "Upper Extremity",
    "common": true,
    "shortcut": false,
    "cptCode": { "id": 6, "cptCode": "73130" },
    "anatomy": { "id": 5, "name": "Hand" },
    "views": { "id": 6, "name": "PA + Lat + Oblique" },
    "description": { "id": 6, "text": "Fingers to distal radius; true oblique." },
    "alias": { "id": 6, "name": "Hand Complete" }
  },
  {
    "id": 7,
    "name": "Wrist 3 View",
    "region": "Upper Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 7, "cptCode": "73110" },
    "anatomy": { "id": 6, "name": "Wrist" },
    "views": { "id": 7, "name": "PA + Lat + Oblique" },
    "description": { "id": 7, "text": "Include distal forearm; lateral thumb up." },
    "alias": { "id": 7, "name": "Wrist Complete" }
  },
  {
    "id": 8,
    "name": "Pelvis 1-2 View",
    "region": "Pelvis",
       "common": false,
    "shortcut": false,
    "cptCode": { "id": 8, "cptCode": "72170" },
    "anatomy": { "id": 7, "name": "Pelvis" },
    "views": { "id": 8, "name": "AP" },
    "description": { "id": 8, "text": "Include iliac crest through proximal femora." },
    "alias": { "id": 8, "name": "Pelvis AP" }
  },
  {
    "id": 9,
    "name": "Hip 2-3 View",
    "region": "Pelvis",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 9, "cptCode": "73502" },
    "anatomy": { "id": 8, "name": "Hip" },
    "views": { "id": 9, "name": "AP + Frog" },
    "description": { "id": 9, "text": "Center over femoral head; frog lateral." },
    "alias": { "id": 9, "name": "Hip Basic" }
  },
  {
    "id": 10,
    "name": "Knee 4 View",
    "region": "Lower Extremity",
    "common": true,
    "shortcut": false,
    "cptCode": { "id": 10, "cptCode": "73564" },
    "anatomy": { "id": 9, "name": "Knee" },
    "views": { "id": 10, "name": "AP + Lat + Tunnel + Sunrise" },
    "description": { "id": 10, "text": "Include joint; patella in profile." },
    "alias": { "id": 10, "name": "Knee Complete" }
  },
  {
    "id": 11,
    "name": "Ankle 3 View",
    "region": "Lower Extremity",
    "common": true,
    "shortcut": true,
    "cptCode": { "id": 11, "cptCode": "73610" },
    "anatomy": { "id": 10, "name": "Ankle" },
    "views": { "id": 11, "name": "AP + Lat + Mortise" },
    "description": { "id": 11, "text": "Include distal tibfib + calcaneus." },
    "alias": { "id": 11, "name": "Ankle Complete" }
  },
  {
    "id": 12,
    "name": "T-Spine 2-3 View",
    "region": "Thoracic Spine",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 12, "cptCode": "72072" },
    "anatomy": { "id": 11, "name": "Thoracic Spine" },
    "views": { "id": 12, "name": "AP + Lat" },
    "description": { "id": 12, "text": "Center at T7; include C7–L1." },
    "alias": { "id": 12, "name": "T-Spine Basic" }
  },
  {
    "id": 13,
    "name": "L-Spine 2-3 View",
    "region": "Lumbar Spine",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 13, "cptCode": "72100" },
    "anatomy": { "id": 12, "name": "Lumbar Spine" },
    "views": { "id": 13, "name": "AP + Lat" },
    "description": { "id": 13, "text": "Include T12–S1." },
    "alias": { "id": 13, "name": "L-Spine Basic" }
  },
  {
    "id": 14,
    "name": "Shoulder 3 View",
    "region": "Upper Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 14, "cptCode": "73030" },
    "anatomy": { "id": 13, "name": "Shoulder" },
    "views": { "id": 14, "name": "AP Int + AP Ext + Y" },
    "description": { "id": 14, "text": "Include proximal humerus + AC." },
    "alias": { "id": 14, "name": "Shoulder Complete" }
  },
  {
    "id": 15,
    "name": "Elbow 3 View",
    "region": "Upper Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 15, "cptCode": "73080" },
    "anatomy": { "id": 14, "name": "Elbow" },
    "views": { "id": 15, "name": "AP + Lat + Oblique" },
    "description": { "id": 15, "text": "Include distal humerus + proximal radius/ulna." },
    "alias": { "id": 15, "name": "Elbow Complete" }
  },
  {
    "id": 16,
    "name": "Forearm 2 View",
    "region": "Upper Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 16, "cptCode": "73090" },
    "anatomy": { "id": 15, "name": "Forearm" },
    "views": { "id": 16, "name": "AP + Lat" },
    "description": { "id": 16, "text": "Include elbow + wrist joints." },
    "alias": { "id": 16, "name": "Forearm 2V" }
  },
  {
    "id": 17,
    "name": "Humerus 2 View",
    "region": "Upper Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 17, "cptCode": "73060" },
    "anatomy": { "id": 16, "name": "Humerus" },
    "views": { "id": 17, "name": "AP + Lat" },
    "description": { "id": 17, "text": "Shoulder through elbow." },
    "alias": { "id": 17, "name": "Humerus 2V" }
  },
  {
    "id": 18,
    "name": "Fingers 3 View",
    "region": "Upper Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 18, "cptCode": "73140" },
    "anatomy": { "id": 17, "name": "Digits" },
    "views": { "id": 18, "name": "PA + Lat + Oblique" },
    "description": { "id": 18, "text": "Include fingertip through MCP." },
    "alias": { "id": 18, "name": "Finger Complete" }
  },
  {
    "id": 19,
    "name": "Toes 3 View",
    "region": "Lower Extremity",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 19, "cptCode": "73660" },
    "anatomy": { "id": 18, "name": "Toes" },
    "views": { "id": 19, "name": "AP + Oblique + Lat" },
    "description": { "id": 19, "text": "Include the toe in question + MTP." },
    "alias": { "id": 19, "name": "Toe Complete" }
  },
  {
    "id": 20,
    "name": "Sinuses 3-4 View",
    "region": "Head",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 20, "cptCode": "70220" },
    "anatomy": { "id": 19, "name": "Sinuses" },
    "views": { "id": 20, "name": "Waters + Caldwell + Lat" },
    "description": { "id": 20, "text": "Include maxillary, frontal, and sphenoid sinuses." },
    "alias": { "id": 20, "name": "Sinus Series" }
  },
  {
    "id": 21,
    "name": "Orbits 4 View",
    "region": "Head",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 21, "cptCode": "70200" },
    "anatomy": { "id": 20, "name": "Orbits" },
    "views": { "id": 21, "name": "Caldwell + Waters + Lat" },
    "description": { "id": 21, "text": "Include both orbits to evaluate for foreign body." },
    "alias": { "id": 21, "name": "Orbits FB" }
  },
  {
    "id": 22,
    "name": "Ribs 3-4 View",
    "region": "Chest",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 22, "cptCode": "71111" },
    "anatomy": { "id": 1, "name": "Chest" },
    "views": { "id": 22, "name": "PA Chest + Oblique" },
    "description": { "id": 22, "text": "Include suspected rib area bilaterally as needed." },
    "alias": { "id": 22, "name": "Rib Series" }
  },
  {
    "id": 23,
    "name": "Sacroiliac Joints 3 View",
    "region": "Pelvis",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 23, "cptCode": "72202" },
    "anatomy": { "id": 7, "name": "Pelvis" },
    "views": { "id": 23, "name": "AP + Obliques" },
    "description": { "id": 23, "text": "Include both SI joints; 15° obliques." },
    "alias": { "id": 23, "name": "SI Joints" }
  },
  {
    "id": 24,
    "name": "Abdomen Acute Series",
    "region": "Abdomen",
    "common": false,
    "shortcut": false,
    "cptCode": { "id": 24, "cptCode": "74022" },
    "anatomy": { "id": 3, "name": "Abdomen" },
    "views": { "id": 24, "name": "Supine + Upright + Chest" },
    "description": { "id": 24, "text": "Evaluate gas pattern + free air; includes chest." },
    "alias": { "id": 24, "name": "Acute Abdomen Series" }
  },
  {
    "id": 25,
    "name": "Chest for PICC Line",
    "region": "Chest",
    "common": false,
    "shortcut": true,
    "cptCode": { "id": 25, "cptCode": "71045" },
    "anatomy": { "id": 1, "name": "Chest" },
    "views": { "id": 25, "name": "AP" },
    "description": { "id": 25, "text": "Portable chest to evaluate PICC tip location." },
    "alias": { "id": 25, "name": "Line Check" }
  }
];


export default ExamsData;
